Access to headless chrome with socat
NeuraLegion/cdp-images pull request #17
Opened 2022-10-20 09:42 UTC by alexkutsan

2022-10-20 21:18 UTC, shevchenkov-neuralegion commented
@alexkutsan I think socat changes have to be added under `chrome` as it was the main purpose of that image (usage of `--headless=chrome` flag).

2022-10-21 16:46 UTC, derevnjuk requested changes
See https://github.com/NeuraLegion/cdp-images/pull/17#issuecomment-1286165244. Also, you have to follow our contributing guidelines. Please adjust the PR title

2022-10-24 12:09 UTC, alexkutsan commented
@derevnjuk  please see updated PR

2022-10-24 18:37 UTC, shevchenkov-neuralegion approved these changes

2022-10-25 06:41 UTC, derevnjuk approved these changes

2022-10-26 09:26 UTC, alonchin approved these changes

2022-10-26 09:26 UTC, merged